services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-multitalent}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - multitalent_net

  api:
    image: ${IMAGE:-multitalent-backend/api:prod}
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - multitalent_net
    command: >
      gunicorn
      -w ${WEB_CONCURRENCY:-2}
      -k gthread --threads ${GTHREADS:-8}
      --timeout ${TIMEOUT:-60}
      -b 0.0.0.0:8000
      app.wsgi:app
    ports:
      - "8000:8000"

  sonar_db:
    image: postgres:15
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - sonar_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - multitalent_net

  sonarqube:
    image: sonarqube:lts-community
    depends_on:
      - sonar_db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
    restart: unless-stopped
    networks:
      - multitalent_net

  prometheus:
    image: prom/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=15d"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
   
    networks:
      - multitalent_net

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SMTP_ENABLED: true
      GF_SMTP_HOST: smtp.gmail.com:587
      GF_SMTP_USER: nivusoftware@gmail.com
      GF_SMTP_PASSWORD: zjfogignioctipkw
      GF_SMTP_FROM_ADDRESS: nivusoftware@gmail.com
      GF_SMTP_FROM_NAME: Grafana
      GF_SMTP_SKIP_VERIFY: false
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - multitalent_net

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8083:8080"
    restart: unless-stopped
    networks:
      - multitalent_net



volumes:
  db_data:
  sonar_db_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  prometheus_data:
  grafana_data:

networks:
  multitalent_net:
    external: true
