sonar.projectKey=multitalent_backend_tita
sonar.projectName=multitalent_backend_tita
sonar.sourceEncoding=UTF-8

sonar.sources=app
sonar.tests=tests

sonar.exclusions=**/__pycache__/**,**/.venv/**,**/.pytest_cache/**,**/migrations/**,**/instance/**

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=pytest-report.xml
sonar.python.bandit.reportPaths=bandit-report.xml
