"""create postulations table

Revision ID: 80923210bb2e
Revises: e358014351ed
Create Date: 2025-09-19 03:18:08.539605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80923210bb2e'
down_revision = 'e358014351ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postulation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('residence_addr', sa.Text(), nullable=True),
    sa.Column('age', sa.SmallInteger(), nullable=True),
    sa.Column('role_exp_years', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('expected_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cv_path', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('applicant_id', 'vacancy_id', name='uq_postulation_applicant_vacancy')
    )
    with op.batch_alter_table('postulation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_postulation_applicant_id'), ['applicant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_postulation_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_postulation_vacancy_id'), ['vacancy_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postulation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_postulation_vacancy_id'))
        batch_op.drop_index(batch_op.f('ix_postulation_status'))
        batch_op.drop_index(batch_op.f('ix_postulation_applicant_id'))

    op.drop_table('postulation')
    # ### end Alembic commands ###
