"""Add url to courses

Revision ID: 907ceb61147b
Revises: 60f1e30e81f2
Create Date: 2025-09-15 03:03:57.343645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '907ceb61147b'
down_revision = '60f1e30e81f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###
