"""add ci and number on postulations

Revision ID: a528d506b57f
Revises: 80923210bb2e
Create Date: 2025-09-19 05:12:46.094322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a528d506b57f'
down_revision = '80923210bb2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postulation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credential', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postulation', schema=None) as batch_op:
        batch_op.drop_column('number')
        batch_op.drop_column('credential')

    # ### end Alembic commands ###
