"""create charges table

Revision ID: b8a9c5c8cabd
Revises: 1c9ab78cdd41
Create Date: 2025-09-11 02:11:43.084169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8a9c5c8cabd'
down_revision = '1c9ab78cdd41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('area', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('charges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_charges_area'), ['area'], unique=False)
        batch_op.create_index(batch_op.f('ix_charges_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_charges_title'))
        batch_op.drop_index(batch_op.f('ix_charges_area'))

    op.drop_table('charges')
    # ### end Alembic commands ###
