"""add status_reason to postulation

Revision ID: bf602b7ef9d6
Revises: 3334321dd035
Create Date: 2025-10-17 03:16:14.259983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf602b7ef9d6'
down_revision = '3334321dd035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postulation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postulation', schema=None) as batch_op:
        batch_op.drop_column('status_reason')

    # ### end Alembic commands ###
