"""ajustes postulation/vacancy

Revision ID: c10db5dc2313
Revises: 63fa68099691
Create Date: 2025-10-02 04:42:11.884237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c10db5dc2313'
down_revision = '63fa68099691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_constraint('interviews_postulation_id_key', type_='unique')

    with op.batch_alter_table('postulation_ai_results', schema=None) as batch_op:
        batch_op.drop_index('ix_postulation_ai_results_postulation_id')
        batch_op.create_index(batch_op.f('ix_postulation_ai_results_postulation_id'), ['postulation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postulation_ai_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_postulation_ai_results_postulation_id'))
        batch_op.create_index('ix_postulation_ai_results_postulation_id', ['postulation_id'], unique=True)

    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.create_unique_constraint('interviews_postulation_id_key', ['postulation_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
