"""create vacancies and vacancy_skills

Revision ID: d27d8de9d269
Revises: 907ceb61147b
Create Date: 2025-09-16 01:35:34.465895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd27d8de9d269'
down_revision = '907ceb61147b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charge_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('modality', sa.String(length=20), nullable=True),
    sa.Column('apply_until', sa.Date(), nullable=False),
    sa.Column('publish_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('headcount', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('headcount >= 1', name='ck_vacancies_headcount_positive'),
    sa.ForeignKeyConstraint(['charge_id'], ['charges.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vacancies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vacancies_apply_until'), ['apply_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacancies_charge_id'), ['charge_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacancies_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacancies_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacancies_modality'), ['modality'], unique=False)
        batch_op.create_index('ix_vacancies_public', ['is_active', 'apply_until', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacancies_publish_at'), ['publish_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacancies_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacancies_title'), ['title'], unique=False)

    op.create_table('vacancy_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('required_score', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(required_score IS NULL) OR (required_score BETWEEN 0 AND 100)', name='ck_vacancy_skill_required_score'),
    sa.CheckConstraint('(weight IS NULL) OR (weight >= 0)', name='ck_vacancy_skill_weight_nonnegative'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vacancy_id', 'skill_id', name='uq_vacancy_skill')
    )
    with op.batch_alter_table('vacancy_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vacancy_skills_skill_id'), ['skill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacancy_skills_vacancy_id'), ['vacancy_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacancy_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vacancy_skills_vacancy_id'))
        batch_op.drop_index(batch_op.f('ix_vacancy_skills_skill_id'))

    op.drop_table('vacancy_skills')
    with op.batch_alter_table('vacancies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vacancies_title'))
        batch_op.drop_index(batch_op.f('ix_vacancies_status'))
        batch_op.drop_index(batch_op.f('ix_vacancies_publish_at'))
        batch_op.drop_index('ix_vacancies_public')
        batch_op.drop_index(batch_op.f('ix_vacancies_modality'))
        batch_op.drop_index(batch_op.f('ix_vacancies_location'))
        batch_op.drop_index(batch_op.f('ix_vacancies_is_active'))
        batch_op.drop_index(batch_op.f('ix_vacancies_charge_id'))
        batch_op.drop_index(batch_op.f('ix_vacancies_apply_until'))

    op.drop_table('vacancies')
    # ### end Alembic commands ###
