"""change psw field to txt type

Revision ID: 031141b384ab
Revises: 70ba041b60fb
Create Date: 2025-09-05 14:17:07.091531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '031141b384ab'
down_revision = '70ba041b60fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicant', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicant', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
