"""personality attempt & answer table

Revision ID: 2d0747612fa2
Revises: c10db5dc2313
Create Date: 2025-10-05 03:27:15.878760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d0747612fa2'
down_revision = 'c10db5dc2313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personality_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postulation_id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('time_limit_sec', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('overall_score', sa.SmallInteger(), nullable=True),
    sa.Column('recommendation', sa.String(length=16), nullable=True),
    sa.Column('traits_json', sa.JSON(), nullable=True),
    sa.Column('pdf_report_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(finished_at IS NULL) OR (started_at IS NOT NULL AND finished_at >= started_at)', name='ck_attempt_times_make_sense'),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['postulation_id'], ['postulation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('personality_attempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personality_attempt_applicant_id'), ['applicant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_personality_attempt_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_personality_attempt_finished_at'), ['finished_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_personality_attempt_postulation_id'), ['postulation_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_personality_attempt_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_personality_attempt_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_personality_attempt_vacancy_id'), ['vacancy_id'], unique=False)

    op.create_table('personality_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_code', sa.String(length=20), nullable=False),
    sa.Column('option_value', sa.SmallInteger(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('option_value >= 0', name='ck_answer_option_non_negative'),
    sa.ForeignKeyConstraint(['attempt_id'], ['personality_attempt.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_code', name='uq_answer_attempt_question')
    )
    with op.batch_alter_table('personality_answer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personality_answer_attempt_id'), ['attempt_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personality_answer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personality_answer_attempt_id'))

    op.drop_table('personality_answer')
    with op.batch_alter_table('personality_attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personality_attempt_vacancy_id'))
        batch_op.drop_index(batch_op.f('ix_personality_attempt_status'))
        batch_op.drop_index(batch_op.f('ix_personality_attempt_started_at'))
        batch_op.drop_index(batch_op.f('ix_personality_attempt_postulation_id'))
        batch_op.drop_index(batch_op.f('ix_personality_attempt_finished_at'))
        batch_op.drop_index(batch_op.f('ix_personality_attempt_expires_at'))
        batch_op.drop_index(batch_op.f('ix_personality_attempt_applicant_id'))

    op.drop_table('personality_attempt')
    # ### end Alembic commands ###
