"""terms acceptance table

Revision ID: 3334321dd035
Revises: 2d0747612fa2
Create Date: 2025-10-15 00:39:07.064605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3334321dd035'
down_revision = '2d0747612fa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terms_acceptances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('doc_path', sa.String(length=512), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['applicant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('terms_acceptances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_terms_acceptances_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terms_acceptances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_terms_acceptances_user_id'))

    op.drop_table('terms_acceptances')
    # ### end Alembic commands ###
