"""US-33: create skills_courses table

Revision ID: 60f1e30e81f2
Revises: 5d401438f7c4
Create Date: 2025-09-15 01:06:23.556721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60f1e30e81f2'
down_revision = '5d401438f7c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills_courses',
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('skill_id', 'course_id')
    )
    with op.batch_alter_table('skills_courses', schema=None) as batch_op:
        batch_op.create_index('ix_skills_courses_course_id', ['course_id'], unique=False)
        batch_op.create_index('ix_skills_courses_skill_id', ['skill_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills_courses', schema=None) as batch_op:
        batch_op.drop_index('ix_skills_courses_skill_id')
        batch_op.drop_index('ix_skills_courses_course_id')

    op.drop_table('skills_courses')
    # ### end Alembic commands ###
